add read faq to send tippers
lbryio/lbry-tipbot pull request #34
Opened 2018-10-04 15:33 UTC by ykris45

i added FAQ 
#hacktobers

2018-10-04 15:40 UTC, tzarebczan commented
LGTM! @filipnyquist please merge when you get a chance.

2018-10-04 15:42 UTC, ykris45 commented
@tzarebczan maybe nikoo777 as assigness sir.. thanks. just get a chance..

2018-10-05 22:07 UTC, nikooo777 commented on bot/modules/tipbot.js
> +DM me with \`${message.content.split(' ', 1)[0]}\` for command specific instructions or with \`!tips\` for all available commands or read our [Tipbot FAQ](https://lbry.io/faq/tipbot-discord) for a mo
there is a typo. `for A more`. drop the `a` please :)

2018-10-05 22:07 UTC, nikooo777 requested changes
typo

2018-10-05 22:34 UTC, ykris45 commented
@nikooo777 done bro

2018-10-08 14:48 UTC, nikooo777 approved these changes

2018-10-08 21:08 UTC, filipnyquist commented
LGTM!

2018-10-08 21:08 UTC, merged